title: Fengxuan Zhang's Homepage
page-top-title: Fengxuan Zhang
top-section-bg-text: Be Open to All Ideas and Learn from Others to Achieve Long-term Success
home-subtitle: Fengxuan Zhang&ensp;|&ensp;张风轩
copyright-text: '&copy; Fengxuan Zhang 2023-2025. All Rights Reserved.'
